version: '3.5'

services:  

    rabbitmq:
        image:  bitnami/rabbitmq:latest
        expose: 
            - "5672"
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_VHOST: smorest
            RABBITMQ_ULIMIT_NOFILES: 128

    redis:
        image: redis:5.0.9-alpine
        expose:
            - "6379"
        command: redis-server

    db:
        image: ssfdust/psql_jieba_swsc:latest
        expose:
            - "5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-smorest-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smorest2021}
            POSTGRES_DB: ${POSTGRES_DB:-smorest-production}
            PGDATA: /data/postgres

    nginx:
        image: nginx:stable-alpine
        ports:
            - "8083:8083"
        volumes:
            - ./deploy/nginx/flask.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - pgadmin
            - rabbitmq
            - web

    web:
        image: ssfdust/smorest-sfs
        volumes:
            - .:/Application 
        restart: on-failure
        expose: 
            - "8000"
        depends_on:
            - db
            - rabbitmq
            - redis
        environment:
            - VIRTUAL_HOST=smorest.local
            - WEB_CONCURRENCY=2

    beat:
        image: ssfdust/smorest-sfs
        volumes:
            - .:/Application 
        depends_on:
            - web
        environment:
            APP: beat

    celery:
        image: ssfdust/smorest-sfs
        volumes:
            - .:/Application 
        depends_on:
            - web
        environment:
            APP: celery

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "8084:8084"
        expose: 
            - "80"
        environment:
            - PGADMIN_LISTEN_PORT=8084
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=admin