apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath --controller
      Deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: beat
  name: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: beat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath --controller
          Deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: beat
    spec:
      containers:
      - env:
        - name: APP
          value: beat
        image: ssfdust/smorest-sfs
        imagePullPolicy: ""
        name: beat
        resources: {}
        volumeMounts:
        - mountPath: /Application
          name: beat-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /Development/smorest-sfs
        name: beat-hostpath0
status: {}
