apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath --controller
      Deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath --controller
          Deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:stable-alpine
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 8083
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-hostpath0
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /Development/smorest-sfs/deploy/nginx/flask.conf
        name: nginx-hostpath0
status: {}
