API_TITLE = 'Smorest-SFS'
API_VERSION = 'v1'

OPENAPI_VERSION = '3.0.2'
OPENAPI_REDOC_PATH = 'redoc'
OPENAPI_REDOC_URL = "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"
OPENAPI_SWAGGER_UI_PATH = 'swagger'
OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
OPENAPI_URL_PREFIX = 'doc'
MODULE_BASE_PREFIX = '/api/v1'

SQLALCHEMY_DATABASE_URI = 'postgresql://smorest-admin:smorest2021@db/smorest-production'
SQLALCHEMY_TRACK_MODIFICATIONS = false

REDIS_URL = 'redis://redis/0'

JWT_SECRET_KEY = '&#34;$)&gt;96ZE`-R*!X?E+wVvUA7@tNBMXu'
JWT_BLACKLIST_ENABLED = true
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
JWT_TOKEN_LOCATION = ['headers', 'query_string']
JWT_QUERY_STRING_NAME = 'token'

BABEL_DEFAULT_LOCALE = 'zh_cn'
BABEL_DEFAULT_TIMEZONE = 'Asia/Shanghai'

MAIL_SERVER = 'smtp.exmail.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = true
MAIL_USERNAME = ''
MAIL_DEFAULT_SENDER = ''
MAIL_PASSWORD = ''

CELERY_RESULT_BACKEND = 'redis://redis/0'
CELERY_REDBEAT_REDIS_URL = 'redis://redis/0'
CELERY_BROKER_URL = "amqp://admin:admin@rabbitmq:5672/smorest"
CELERY_IMPORTS = ["smorest_sfs.tasks"]

PREFERRED_URL_SCHEME = 'http'
AMQP_URL = 'amqp://admin:admin@rabbitmq:5672/smorest'

[CELERY_BEAT_SCHEDULE.logger]
task="get-logger"
schedule=30
