OPENAPI_VERSION = '3.0.2'
OPENAPI_REDOC_PATH = 'redoc'
OPENAPI_REDOC_URL = "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"
OPENAPI_SWAGGER_UI_PATH = 'swagger'
OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
OPENAPI_URL_PREFIX = 'doc'
MODULE_BASE_PREFIX = '/api/v1'

SQLALCHEMY_DATABASE_URI = 'postgresql://smorest-admin:smoret2019@localhost/smorest-testing'
SQLALCHEMY_TRACK_MODIFICATIONS = false

JWT_SECRET_KEY = '8TI8/KpMArmw9ZVtrXA&amp;=7w\&amp;I$wbX'
JWT_BLACKLIST_ENABLED = true
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
JWT_TOKEN_LOCATION = ['headers', 'query_string']
JWT_QUERY_STRING_NAME = 'token'

BABEL_DEFAULT_LOCALE = 'zh_cn'
BABEL_DEFAULT_TIMEZONE = 'Asia/Shanghai'

MAIL_SERVER = 'smtp.exmail.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = true
MAIL_USERNAME = ''
MAIL_DEFAULT_SENDER = ''
MAIL_PASSWORD = ''

CELERY_RESULT_BACKEND = 'redis://'
CELERY_REDBEAT_REDIS_URL = 'redis://'
CELERY_BROKER_URL = "amqp://"
CELERY_IMPORTS = ["smorest_sfs.tasks"]

PREFERRED_URL_SCHEME = 'http'
AMQP_URL = 'amqp://'

[CELERY_BEAT_SCHEDULE.logger]
task="get-logger"
schedule=30